function [fitresult, gof] = createFitEnthalpy(X, Y, Z)
%CREATEFIT(T,B,L_PHI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : T
%      Y Input : b
%      Z Output: L_phi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Feb-2021 11:49:42


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X, Y, Z );

% Set up fittype and options.
ft = fittype( 'p00/x + p01*y^(1/2)/x + p02*y/x + p03*y^(3/2)/x +       p10 + p11*y^(1/2) + p12*y + p13*y^(3/2) +      p20*x +p21*x*y^(1/2) + p22*y*x + p23*x*y^(3/2)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.913375856139019 0.63235924622541 0.0975404049994095 0.278498218867048 0.546881519204984 0.957506835434298 0.964888535199277 0.157613081677548 0.970592781760616 0.957166948242946 0.485375648722841 0.8002804688888];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );
%figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'L_phi vs. T, b', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T (K)', 'Interpreter', 'none' );
ylabel( 'b (mol/kg)', 'Interpreter', 'none' );
zlabel( 'L_phi (J/g)', 'Interpreter', 'none' );
view( -53.2, 26.2 );


